version: "3.8"

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-amaneko
    environment:
      POSTGRES_DB: amaneko
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5430:5432"

  redis:
    image: redis:7.2.0-alpine
    container_name: redis-amaneko
    command: ["redis-server", "--requirepass password"]
    ports:
      - "127.0.0.1:6380:6379"
