name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**/*.md"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-nightly:
    name: Build and publish (nightly)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/killbasa/amaneko:nightly
            ghcr.io/killbasa/amaneko:${{ github.sha }}

  publish-production:
    name: Build and publish (production)
    runs-on: ubuntu-latest
    environment: Production
    needs: publish-nightly
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new tag
        run: docker buildx imagetools create ghcr.io/killbasa/amaneko:${{ github.sha }} --tag ghcr.io/killbasa/amaneko:stable
